[preview]
enable = true
max_width = 200   # Set a larger width for the preview pane
max_height = 150    # Set a larger height for the preview pane

[preview.commands]
image = ["ueberzug-layer"]  # Use ueberzug for rendering images

