general.import = [
    "~/.config/alacritty/themes/themes/midnight_haze.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.85
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"

size = 17
