

[env]
term = 'xterm-color'

[window]
padding.x = 10
padding.y = 10
dimensions = { columns = 110, lines = 35 }
decorations = "buttonless"


position = { x = 370, y = 180 }

blur = true

opacity = 0.85
option_as_alt = 'both'


[font]

normal.family = 'MesloLGS Nerd Font Mono'


size = 17

[general]
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
